### ISSUE TITLE
Ansible error while deploying to distributed environment

### ISSUE THREAD

**Issue by cagataygurturk** [apache/incubator-openwhisk#2220]
Hello,

I am trying to deploy OpenWhisk to an OpenStack environment using the instructions. I create a clean machine to deploy the stack but when I run

`ansible-playbook -i environments/distributed provision_env_dist.yml`

command I get

`ERROR! ERROR! environments/distributed/templates/hosts.j2:8: Expected key=value host variable assignment, got: for`

Ansible version: ansible 2.0.0.2

Any ideas?

**Comment by digmore** [comment]
Hi,

I hit the same error message just now when attempting to distribute the deployment across existing hosts. The error message led me to ansible/ansible#14312.

After adding the following to the default section of ansible.cfg I was able to get past this error:
`inventory_ignore_extensions = templates`

I skipped the provisioning step you are running though, so my case is a little different. Hope it helps though.

**Comment by rabbah** [comment]
@digmore thanks for the tip. Unfortunately these scripts have rotted a bit and we need to bring them back in line. The plan is to separate them into the [devtools](https://github.com/apache/incubator-openwhisk-devtools) repository and add continuous integration testing to prevent breakage in the future.

In the meantime, did you consider if the alternate deployment method (used by Adobe and others) available in that repo might be of use to you?

**Comment by rabbah** [comment]
@digmore thanks for the tip. Unfortunately these scripts have rotted a bit and we need to bring them back in line. The plan is to separate them into the devtools repository and add continuous integration testing to prevent breakage in the future.

In the meantime, @cagataygurturk did you consider if the alternate deployment method (used by Adobe and others) available in that repo might be of use to you?

**Comment by rabbah** [comment]
devtools repo: https://github.com/apache/incubator-openwhisk-devtools

**Comment by cagataygurturk** [comment]
I was not even aware of that repo. So I skipped yesterday the error message with the same workaround that @digmore mentioned and today I was about to go on with other steps. If you consider those scripts rotten, should I completely leave them and use this repo?

**Comment by rabbah** [comment]
> If you consider those scripts rotten, should I completely leave them and use this repo?

There's value is fixing them again and so if you do get them working again and want to offer pull request we'll of course accept it... and encourage it.

The devtools repo is where we will move these playbooks soon (and we will add a readme tip to link there for alternative deployments). Thanks for pointing that out.

I mentioned it since I didn't know the amount of effort it would take to get these deployment scripts working again (not having tried to use or fix them myself).

**Comment by cagataygurturk** [comment]
We gave a try to docker-compose deployment but we are also stuck in "waiting for the Whisk controller to come up ..." step. The controller log gives this result:

```
ubuntu@openwhisk:~$ tail -f ~/tmp/openwhisk/controller/logs/controller_logs.log
[2017-05-09T10:19:54.138Z] [INFO] [??] [Config] environment set value for kafka.host
[2017-05-09T10:19:54.138Z] [INFO] [??] [Config] environment set value for db.password
[2017-05-09T10:19:54.138Z] [INFO] [??] [Config] environment set value for db.provider
[2017-05-09T10:19:54.140Z] [INFO] [??] [Config] environment set value for limits.triggers.fires.perMinute
[2017-05-09T10:19:54.140Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.concurrent
[2017-05-09T10:19:54.140Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.perMinute
[2017-05-09T10:19:54.141Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.concurrentInSystem
[2017-05-09T10:19:54.141Z] [INFO] [??] [WhiskConfig] reading properties from consul at consul.docker:8500
[2017-05-09T10:19:57.323Z] [WARN] [??] [WhiskConfig] failed to read properties from consul: null
[2017-05-09T10:19:57.334Z] [ERROR] [??] [Controller] Bad configuration, cannot start.
```

We have been seriously considering OpenWhisk for our production but it seems we can't even test it for now...

**Comment by mrutkows** [comment]
@cagataygurturk Seeing the ERROR line you posted:
_ERROR! ERROR! environments/distributed/templates/hosts.j2:8: Expected key=value host variable assignment, got: for_

Not really knowing much about the dist. env. install for Ansible, but looking at the Mac install I thought it was odd to see that your ERROR line included a file NOT valid or used for distributed....

Are you trying to deploy remotely from a Mac and the Ansible is picking up your local environment versus the target (dist. environment)?  

Found this in the dist. README:
_By default, if you omit the -i parameter in Ansible commands, the local environment will be used._

again, I do not know much about the dist. install but if your target is not a bunch of Mac OSX machines, then Ansible is picking up the wrong env.

**Comment by rabbah** [comment]
well now i'm sorry i suggested using devtools :( @ddragosd could probably spot this quickly.

**Comment by cagataygurturk** [comment]
@mrutkows I exactly used `ansible-playbook -i environments/distributed provision_env_dist.yml` but after that I ended up removing `hosts.j2` file and hardcoding server ip's in `environments/distributed/hosts` file. But the next steps were also failure.

Docker-compose deployment seemed promising, and I thought we could scale it up easily using Docker Swarm but I think Docker-Compose needs some updates. It is for example using `links` directive and as it seems that containers can't see each other (my conclusion was that controller container can't see consul) because of that.

I'll work on it a bit more and post updates.

**Comment by kkbankol-ibm** [comment]
@cagataygurturk , which error did you get after setting up your hosts file? Were you able to successfully run the `ansible all -i environments/distributed -m ping` command? 

Also, I'm not too sure about that `inventory_ignore_extensions = templates` parameter, we want to just skip that single broken template file, not all of them. You can also reach out to me on the Openwhisk slack channel if you'd like, my handle there is kkbankol

**Comment by cagataygurturk** [comment]
@kkbankol-ibm it was pinging. I remember that it was complaining about some software was not installed in other machines and before fixing that issue i saw docker-compose thing and left the installation. I will try better with required softwares in target machines and give feedback.

**Comment by digmore** [comment]
Sorry to crash this issue, but I seem to be working through the same challenges that @cagataygurturk is.

I managed to get the deployment working with the original distributed deployment playbooks and a manually configured hosts file. Following the inventory issue there wasn't much more to change to get something running. I have created PR openwhisk/openwhisk#2227 with the few modifications that got me through. It may be worth a try if the compose deployment is problematic?

Also I found it was important that the consul instance in the inventory was specified as an IP and not a DNS name. The inventory name is used by the playbook in a consul config item that only supports IP addresses. Using a domain name led to having a consul container stuck in the restarting state, which could not be interrogated.

**Comment by rabbah** [comment]
Awesome!

**Comment by ddragosd** [comment]
what should the design be here ? 

Previously, even with no properties in Consul, the controller would still start, ignoring the fact that consul doesn't have properties. I'm not sure what the approach should be for docker-compose, Mesos, Kube, either. 

Currently I'm thinking that we should fix the controller to ignore consul, but I'd like to understand more about the design, in case I'm missing something.

**Comment by markusthoemmes** [comment]
@ddragosd I'm pushing to get Consul out as a whole. We don't need it. I've written a proposal for the config value on the dev list. Once we got that done, we can safely remove consul without any more sideeffects.

**Comment by fernandodelaiglesia** [comment]
Precisely I failed in getting consul running.

On executing ansible-playbook -i environments/distributed openwhisk.yml
in task
TASK [consul : wait until the Consul Server/Agent in this host is up and running] ***
I get 
FAILED - RETRYING: TASK: consul : wait until the Consul Server/Agent in this host is up and running (11 retries left).

The container stays in Restaring state for ever
root@consul-servers-1:~# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS                                                                                                                                                  NAMES
f8ced4b98ec3        consul:0.7.0        "docker-entrypoint.sh"   39 seconds ago      Restarting (2) 11 seconds ago   0.0.0.0:8300-8302->8300-8302/tcp, 0.0.0.0:8400->8400/tcp, 0.0.0.0:8301-8302->8301-8302/udp, 0.0.0.0:8500->8500/tcp, 0.0.0.0:8600->8600/udp, 8600/tcp   consul
root@consul-servers-1:~# docker logs consul
/usr/local/bin/docker-entrypoint.sh: exec: line 97: consul agent -config-dir /consul/config: not found
/usr/local/bin/docker-entrypoint.sh: exec: line 97: consul agent -config-dir /consul/config: not found
/usr/local/bin/docker-entrypoint.sh: exec: line 97: consul agent -config-dir /consul/config: not found
/usr/local/bin/docker-entrypoint.sh: exec: line 97: consul agent -config-dir /consul/config: not found
(12 times)

In addition to this the registrators in the rest of nodes stay in Restaring as well, for example

ubuntu@edge-1:~$ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                         PORTS               NAMES
26f80577e22e        gliderlabs/registrator   "/bin/registrator -ip"   6 minutes ago       Restarting (1) 2 minutes ago                       registrator

Previously I corrected the question with the "hosts" and the apigateway and edge names

cat hosts
; the first parameter in a host is the inventory_hostname which has to be
; either an ip
; or a resolvable hostname

; used for local actions only
ansible ansible_connection=local
[registry]
172.16.3.50
[edge]
172.16.3.51
[apigateway:children]
edge
[controllers]
172.16.3.52
[kafka]
172.16.3.53
[consul_servers]
172.16.3.54
[invokers]
172.16.3.55
172.16.3.56
[db]
172.16.3.57

(consul_servers as an IP)

I tryed a lot of things but without success. 

Teh problem looks like the one in the last paragraph by @digmore , which config file do you refer to? /consul/config/config.json --> /tmp/consul/config.json?. If so, I have

root@consul-servers-1:~# cat /tmp/consul/config.json
{
    "server": true,
    "data_dir": "/consul/data",
    "ui": true,
    "log_level": "WARN",
    "node_name": "172.16.3.54",
    "client_addr": "0.0.0.0",
    "advertise_addr": "172.16.3.54",
    "ports": {
        "dns": 8600
    },
    "bootstrap": true,
    "disable_update_check": true


Any ideas?
Thanks a lot

**Comment by hsane2001** [comment]
@fernandodelaiglesia -> I hit the same issue where Consul would hang on coming up in the native environment, I resolved it when I unset PROXY variables in my environment.

**Comment by davglass** [comment]
I'm having a similar error, I wrestled with it all day yesterday and still can't figure out the issue. I have a raw OpenStack Ocata deployment with a single boot strapper node that I am executing the ansible commands from. I'm currently running from the `master` branch. I have a single deployment that worked perfect. My next test was to use OpenStack to deploy a scalable distributed system. 

The error I get when I run `ansible-playbook -i environments/distributed provision_env_dist.yml` is:

```
TASK [set vars] **********************************************************************************************************************************************
Tuesday 06 March 2018  14:37:45 +0000 (0:00:00.045)       0:00:01.693 ********* 
fatal: [ansible]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was:
 'ansible.vars.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'name'\n\nThe error appears to have been in '/home/ubuntu/openwhisk/ansible/boot_instances_dist.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# TODO, in \"with_instance\" loops, the \"instance\" variable that is passed in gets unset, look up the proper way to do nested loops\n- name: set vars\n  ^ here\n"}
```

Full error output here: https://gist.github.com/davglass/77b5079a65abde6416095d5db5699212

Any help would be very appreciated, thanks!

**Comment by rabbah** [comment]
@davglass would you consider a kube based deployment?

i'm afraid these playbooks are not supported and break from time to time because of a lack of test coverage, and will need to dig into the failure to see what's wrong/how to fix.

**Comment by rabbah** [comment]
We have removed these playbooks since they aren't tested and maintained. We'll need to rethink the setup infra setup, but for a distributed deployment, adapting the environment in `local` should suffice.
